import socket
import threading
import time
import json
import os
from client_parser import Parser
from gui import Gui,Main_Window



class Client:
    def __init__(self):
        self.SERVERPORT = 5050
        self.HEADERSIZE = 64
        self.SERVERIP = "192.168.1.191"
        self.SERVERADDR = (self.SERVERIP, self.SERVERPORT)
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        # flag that indicates whether we have to send message with current state
        self.to_send = False
        self.message_state = {
            "from": "a",
            "to": "a",
            "text": "",
            "time": "",
            "command": "",
            "delay": 0,
            # flag that indicates whether message should be resent or audited by server
        }
        self.user_commands = ["-s:", "-delay:", "-swtch:",
                              "-d:", "-delayall:"]  # for server from user , forgot about -info
        self.server_commands = {}  # commands generated by server
        self.hidden_commands = {}  # notification commands
        self.test_mode = False  # doesn't permit access to the Internet
        self.reset_delay = True
        # commands that are not sent to server
        self.setup_commands = ["-delay:", "-swtch:", "-delayall:"]
        self.help_string = "This is help string "  # * needs change
        self.logged_in = False
        self.gui = None 

    def start(self):
        if not self.test_mode:
            try:
                self.sock.connect(self.SERVERADDR)
            except:
                print("ServerError: try again later")
                self.exit_client()
            else:
                self.login_process(self.sock)
                gui = Gui(Main_Window,self)
                gui.start()
                data_thread = threading.Thread(
                    target=self.receive_data, args=(self.sock,))
                data_thread.start()

    def get_time(self):
        return time.ctime()
    
    def exit_client(self):
        os._exit(0)
        
    def is_from_server(self, msg):
        if msg["from"] == "SERVER":
            return True
        return False

    def receive_data(self, socket):
        #! client doesn't differentiate server messages from user messages
        while True:
            message_len = socket.recv(64)
            formatted_msg_len = parser.format_message_length(
                message_len, False)
            message = socket.recv(formatted_msg_len)
            decoded_message = parser.format_message(message, for_server=False)
            is_server_message = self.is_from_server(decoded_message)
            if is_server_message:  # we don't send notifications for server messages
                self.execute_server_generated_commands(decoded_message)
            else:
                print(decoded_message)
                self.deliv_response(decoded_message)

    # one star near the message
    def execute_server_generated_commands(self, msg):  # ? obj<- -> None
        
        command = msg["command"]
        error = msg["error"]
        if error:
            print(msg)
        if command == "-login_accept:":
            self.logged_in = True
            obtained_account_val = msg["to"]
            self.change_message_property("from", obtained_account_val)
        elif command == "-usr_deliv_success:" or command == "-serv_deliv_success:":
            if command == "-usr_deliv_success:":
                print("firststar")
            else:
                print("secondstar")
        elif command == "-account_status:":
            print("-account_status: " ,msg["text"])
        return

    def deliv_response(self, message):  # ? obj<- -> None
        response_message = {
            "from": self.message_state["from"],
            "text": "",
            # one who sent us this message gets response
            "to": message["from"],
            "time": self.get_time(),
            "command": "-delivery_confirmed:",
            "delay": 0
        }
        self.send_deliv_response(response_message)
        return

    def login_process(self, socket):  # ? -> None
        while not self.logged_in:
            account_name = input("Type name of your account: ")
            login_message_obj = {"text": account_name,  # ! if account_name is disconnect -> disconnect
                                 "from": "unknown",
                                 "delay": 0,
                                 "time": parser.get_time()
                                 }  # we create new message object not to change our global message state!
            login_message_formatted = parser.format_message(
                login_message_obj, for_server=True)
            message_len_formatted = parser.format_message_length(
                len(login_message_formatted), for_server=True)
            socket.send(message_len_formatted)
            socket.send(login_message_formatted)
            self.receive_login_response(socket)
        return
        # add field for password

    # ? string <- -> [int or string]
    def change_message_property(self, name, value):
        self.message_state[name] = value

    def receive_login_response(self, socket):
        
        message_len = socket.recv(64)
        formatted_msg_len = parser.format_message_length(
            message_len, False)
        message = socket.recv(formatted_msg_len)
        decoded_message = parser.format_message(message, for_server=False)
        self.execute_server_generated_commands(decoded_message)
        return

    def update(self, update):  # ? obj<- -> None
        if update["command"] not in self.setup_commands:
            self.to_send = True  # sending immediately if not delay or switch comamnd
            if update["command"] == "-d:":
                exit_timer = threading.Timer(2.0, self.exit_client)
                exit_timer.start()
                # !need to clean message state # except from, time, not notif
            if update["command"] == "-s:":
                self.change_message_property("text", update["text"])
            self.change_message_property("command", update["command"])
            self.change_message_property("time", update["time"])

        # don't consider time for delay and switch commands
        elif update["command"] == "-delay:":
            # we don't delay disconnect messages
            self.reset_delay = True
            self.change_message_property("delay", int(update["text"]))

        elif update["command"] == "-swtch:":
            self.change_message_property("to", update["text"])

        elif update["command"] == "-delayall:":
            self.reset_delay = False
            self.change_message_property("delay", update["text"])

    # updates message state and sends message

    def update_message_state(self, msg):  # ? obj <- -> None
        self.update(msg)  # updates message state
        # print(self.message_state, " message obj") # for testing
        if self.to_send == True:  # if send flag is true
            self.to_send = False
            raw_message = self.message_state
            formatted_message = parser.format_message(raw_message)
            formatted_msg_len = parser.format_message_length(
                len(formatted_message))
            if self.reset_delay == True:
                self.change_message_property("delay", 0)
            self.send(formatted_msg_len, self.sock)
            self.send(formatted_message, self.sock)
            # reset delay
        return

    def send(self, msg, socket):  # ? bytes socket<-  -> None
        if not self.test_mode:
            try:
                socket.send(msg)
            except:
                print("ServerError: try again later")
        else:
            print(msg)

    def send_deliv_response(self, msg):  # ? object <- -> None
        msg_formatted = parser.format_message(msg, for_server=True)
        msg_len_formatted = parser.format_message_length(
            len(msg_formatted), for_server=True)
        self.sock.send(msg_len_formatted)
        self.sock.send(msg_formatted)
        return


parser = Parser()
client = Client()
client.start()
